import { NextResponse } from "next/server";
import { promises as fs } from "fs";
import path from "path";

export const dynamic = "force-dynamic";

export async function GET() {
  try {
    // Serve pre-fetched static data (generated by scripts/fetch-data.mjs)
    // Temple's REDCap blocks API calls from Vercel's servers,
    // so we fetch data locally and deploy it as a static JSON file.
    const dataPath = path.join(process.cwd(), "public", "data", "participants.json");
    const raw = await fs.readFile(dataPath, "utf-8");
    const data = JSON.parse(raw);
    return NextResponse.json(data);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json(
      { error: "Failed to load participant data", details: message },
      { status: 500 }
    );
  }
}
